project_id = "smvbhwaupvbxqxqxzzjx"

[functions.link-telegram]
verify_jwt = false

[functions.user-role]
verify_jwt = false

[functions.lead-create]
verify_jwt = false

[functions.client-stock-update]
verify_jwt = false

[functions.enqueue-notification]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false